name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
    HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
    HF_PATH: ${{ secrets.HF_PATH }}
    REDIS_HOST: ${{ secrets.REDIS_HOST }}
    REDIS_PORT: ${{ secrets.REDIS_PORT }}
    REDIS_USER: ${{ secrets.REDIS_USER }}
    REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get the data
      run: bash scripts/get_data.sh

    - name: Generate combinations
      run: python3.11 -m simian.combiner

    - name: Run tests
      run: python3.11 -m simian.tests.__run__

    - name: Check test results
      if: failure()
      run: |
        echo "Some tests failed. Please check the test output for more details."
        exit 1