name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run install_blender_linux.sh
      run: bash scripts/install_blender_linux.sh

    - name: Get the data
      run: bash scripts/get_data.sh

    - name: Generate combinations
      run: python simian/combiner.py

    - name: Run tests
      run: HF_TOKEN=${{ secrets.HF_TOKEN }} python tests/__run__.py

    - name: Check test results
      if: failure()
      run: |
        echo "Some tests failed. Please check the test output for more details."
        exit 1